language: node_js

node_js:
  - "lts/*"

install:
  - npm i
  - npm i -g mocha

script:
  - npm run test

after_success: npm run coverage

cache:
  directories:
    - node_modules

branches:
  only:
    - master